const actionsTypes = {
	IS_AUTHENTICATED: "IS_AUTHENTICATED",
	LOGOUT: "LOGOUT",
	LOGIN_START: "LOGIN_START",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_ERROR: "LOGIN_ERROR",
};

export default actionsTypes;
